spring:
  application:
    name: teste-pratico-java-backend

  rabbitmq:
    host: localhost
    port: 5672
    username: VR
    password: software
    listener:
      simple:
        acknowledge-mode: manual

app:
  rabbitmq:
    queue: orders.inbound.carlos
    dlq: orders.inbound.carlos.dlq
    dlx: orders.inbound.carlos.dlx
    success-queue: orders.status.success.carlos
    failure-queue: orders.status.failure.carlos
